prepare:
  split: 0.20
  seed: 20170428

featurize:
  max_features: 800
  ngrams: 4

train:
  seed: 20170428
  n_est: 250
  min_split: 88


checkpoints-playground:
  seed: 473987
  lr: 0.0001
  weight_decay: 0
